spring:
  datasource:
    url: jdbc:mysql://localhost:3306/michelesei
    username: root
    password: Borraco1990
jpa:
    database: mysql
    show_sql: true
    hibernate:

      ##mi rifa il db da zero
    ##in fase di aggiunta usare update
    ddl-auto: create



##server:
##port: 7070
  ##myCustomEnvs:
    ##devName: Andreamax